### ISSUE TITLE
Flight is still displayed when flying outside the canvas

### ISSUE THREAD

**Issue by oliverwhk** [davetheunissen/AzureFunctionsWorkshop#4]
Hi Dave, I attended the .net user group yesterday.

Just wondering if following logic means the system would still show the flight on the canvas although it might have flied outside the boundary?
The fact that "planes" array is persisted across each time flight API is invoked.

```
let datasource;
let planes = [];

function ProcessFlightData(flight) {
    console.log(flight);

    var newFlightPin = new atlas.Shape(new atlas.data.Point([flight.longitute, flight.latitude]), flight.id);
    newFlightPin.addProperty('name', flight.callsign);
    newFlightPin.addProperty('altitude', flight.altitude);
    newFlightPin.addProperty('rotation', flight.trueTrack);

    planes[flight.id] = newFlightPin;
    datasource.setShapes(Object.values(planes));
}
```

If it's an issue, then the possible quick fix would be moving the line of code inside function "ProcessFlightData".

**Comment by davetheunissen** [comment]
You are right, the plane array should probably be cleared at some point. That said, this probably isn't the most optimal solution and is simply for demo purposes.

A cleaner approach my be to create a redraw function that handles map redraws separately from data-source updates
